### ISSUE TITLE
UnboundLocalError: local variable 'foldername' referenced before assignment

### ISSUE THREAD

**Issue by bbarrows89** [beatleuk/gdfl#4]
`(venv)  ✘  ~/Desktop/googledrive  python3 goog.py
Traceback (most recent call last):
  File "goog.py", line 309, in <module>
    main()
  File "goog.py", line 242, in main
    if not foldername:
UnboundLocalError: local variable 'foldername' referenced before assignment`

**Comment by ghost** [comment]
@bbarrows89 
Did you solve the above problem? I have the same :-/
Would love to get this file running.

Cheers
John

**Comment by beatleuk** [comment]
Hi both, I'm looking into this now, just didn't see the message from @bbarrows89 until @JohnPfandler commented, so will get cracking on it now.

**Comment by beatleuk** [comment]
I have amended the script, please re-run and let me know if it 's resolved

**Comment by ghost** [comment]
Hi, I'm afraid it's not working but I'm very sure it's because I'm doing something very wrong. To be honest I need a little help in setting this whole thing up. 

I followed all the steps pointed out in the readme 1 through 8. As of then I'm stuck. 
I created a new python file and within the same folder I put the .json. The first time I tried to run this I was actually directed to the google sign-in window and after that it read something like the "flow being completed" or so. That was the last thing that seemed to work.

When running the script now I get various errors. I had to import a few modules, luckily pycharm suggested which ones. Now there's another error I can't fix. It reads

Traceback (most recent call last):
  File "C:/Users/jpfan/PycharmProjects/websiteszhh2/webbpage.py", line 9, in <module>
    from apiclient import errors, discovery
ImportError: cannot import name 'errors' from 'apiclient' (C:\Users\jpfan\PycharmProjects\websiteszhh2\venv\lib\site-packages\apiclient\__init__.py)

What is more, I wonder what to do next, that issue hopefully being resolved one day. Where would I eventually save the file and where do I specify the folder I want the tree of?
Sorry if this seems like a very dumb question, better let you know that I have very minimal programming knowledge. 

What I (eventually) want is the following: 
I want a webpage where I can browse a publicly shared folder. I don't want this to be in the google drive application since there are too many options as of what to do with files and I want all those options eliminated, just plain viewing. Since the shared folder needs its sharing settings set to "public" I don't have any control what viewers of this folder might do with the files. To keep control, I had the following idea: Just let people browse the files on a webpage without actually being directed to google drive. They'd be able to download single files but not able to copy the whole link of the public folder and share it elsewhere.

Before I was trying to use embeddedfolderview with an iframe but that method can only show files in one folder. Once there is another folder in the previous one, one is directed to the official google drive application which causes all the trouble.

I don't expect anyone to fix this thing for me entirely, but helping me getting closer would be a very kind thing to do ;-).

Cheers
John

**Comment by beatleuk** [comment]
Hi John,

Sorry you're having issues but it does sound like you haven't authorised the project properly.

After reading through your requirements I can say that this script would not be ideal for you as althoiugh it does produce a folder structure of all the folders and their files it does make the full url available and clicking on any of the hyperlinks would open that file or folder in the relevant Google application beit Drive, Docs, Sheets or Slides. 
Without masking the url to the file I you'll find it difficult to stop people from getting the whole url and being able to share it elsewhere.

You could always contact a Google Partner, Sites or web developer to see what they can do for you but off the top of my head I don't know of anything that would meet your requirements.

Regards
Lee
